import localFont from "next/font/local";
import "./globals.css";
import SpaceStarsBackground from "./components/SpaceStarsBackground";
import Sound from "./components/sound";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AK Web-Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/images/helmet.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <SpaceStarsBackground />
        {/* going to add spacestars background to each page so we add it to the layout page.*/}

        <Sound />
        {/* Above is our sound component */}

        <div id="my-modal" />
        {/* Parent container for our modal */}
      </body>
    </html>
  );
}
